### ISSUE TITLE
3D Localisation with four anchors

### ISSUE THREAD

**Issue by thire66** [jremington/UWB-Indoor-Localization_Arduino#15]
Hey, I have the following issue:

I've set up four anchors for 3D localization. Next, I'm retrieving the distances to each anchor from the tag. Everything is working fine until I reach the point where the fourth anchor is addressed. At that moment, suddenly, the distance measurement for one of the previously working anchors is no longer accurate."

```
from: 1A, Range: 1.70m	 RX power: -64.92 dBm
from: 3C, Range: 2.12m	 RX power: -77.70 dBm
from: 2B, Range: 1.14m	 RX power: -79.21 dBm <-working fine
from: 1A, Range: 1.73m	 RX power: -64.77 dBm
from: 3C, Range: 2.16m	 RX power: -77.11 dBm
from: 2B, Range: 1.17m	 RX power: -78.97 dBm
Device added: 4D
from: 1A, Range: 1.72m	 RX power: -64.86 dBm
from: 3C, Range: 2.19m	 RX power: -77.62 dBm
from: 2B, Range: 45.12m	 RX power: -79.96 dBm <-broken
from: 4D, Range: 2.06m	 RX power: -87.39 dBm
from: 1A, Range: 1.72m	 RX power: -64.81 dBm
from: 3C, Range: 2.17m	 RX power: -75.71 dBm
from: 2B, Range: 254.88m	 RX power: -80.21 dBm <-broken
from: 4D, Range: 2.04m	 RX power: -88.55 dBm
from: 1A, Range: 1.73m	 RX power: -64.84 dBm
from: 3C, Range: 2.16m	 RX power: -75.38 dBm
from: 2B, Range: 206.40m	 RX power: -79.97 dBm <-broken
```

Do you have any ideas to solve this problem?

**Comment by jremington** [comment]
Sorry, I have not seen anything like that, with a four anchor configuration.  Post the code you are using.

There do appear to be unsolved problems with the original DW1000 library when five anchors are present.

**Comment by thire66** [comment]
Hey, thank you very much. I had converted the 4-anchor example into a FreeRTOS variant, and it seems that a vTaskDelay ended up in the wrong place, and my stack size was too small. Now it works!

**Comment by hsutzu** [comment]
Hi, I am using 4 anchors and 1 tag, and when I use them at the same time, I find out there is a large error, for example, it stayed at 1.5 meters, but suddenly it jumped to 33.7 meters, and then dropped slowly, after that it still may turn into large range number occasionally, has anyone had the same problem and have any solutions on it?

I want to do the 3D localization but with this error, I cannot do the localization, since the original anchor to tag range is wrong, and the filter did not help.

I am having the same issue as you can I ask how you solve this?
