### ISSUE TITLE
Library Support for Muliple Tags?

### ISSUE THREAD

**Issue by saishivareddy** [jremington/UWB-Indoor-Localization_Arduino#17]
Hi,

I have used this library for ESP32 and DWM1000 for Two way ranging between two devices (Anchor and a Tag). But I Want to do this with Multiple tags (Min. 3). Can you please let me know what things I have to do modify to get this done?

Thanks,
Shiva

**Comment by jremington** [comment]
You will need to calibrate 3 or 4 anchors, mount them around the room and measure their locations in meters from some arbitrary origin. One room corner is a convenient origin.

Run the setup_tag and setup_anchor examples for each, in order to assign a device address and set the tag or anchor mode.

The, run one of the three examples on the tag (for 3D location and 4 anchors, use ESP32_UWB_tag3D_4A. But first, make sure to enter the correct anchor IDs and positions in the tag code.
